### ISSUE TITLE
Contao 4.9 Kompatibilität

### ISSUE THREAD

**Issue by Total-Reality** [BugBuster1701/contao-visitors-bundle#106]
Leider funktioniert die Erweiterung nicht mit Contao 4.9.16. Oder geht sie allgemein nicht mit Contao 4.9?
Das wäre sehr schlecht, da wir die Erweiterung dann bei keinem Projekt mehr einsetzen können, also dann erst wieder 2024, wenn der LTS von Contao 4.9 abgelaufen ist :(

**Comment by BugBuster1701** [comment]
Was geht denn nicht?
Welche Version von Visitors wurde installiert?

**Comment by Total-Reality** [comment]
Die Erweiterung kann nicht installiert werden.

Problem 1
    - bugbuster/contao-visitors-bundle[1.7.0-RC1, ..., 1.7.0-RC2] require contao/core-bundle ~4.10 -> satisfiable by contao/core-bundle[4.10.0-RC1, ..., 4.11.5].
    - You can only install one version of a package, so only one of these can be installed: contao/core-bundle[4.0.0-beta1, ..., 4.11.5].
    - contao/calendar-bundle 4.9.16 requires contao/core-bundle 4.9.16 -> satisfiable by contao/core-bundle[4.9.16].
    - contao/calendar-bundle is locked to version 4.9.16 and an update of this package was not requested.
    - Root composer.json requires bugbuster/contao-visitors-bundle ^1.7@RC -> satisfiable by bugbuster/contao-visitors-bundle[1.7.0-RC1, 1.7.0-RC2].
Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

**Comment by BugBuster1701** [comment]
Steht ja ganz eindeutig da, die Version 1.7.0-RC1 und RC2 ist nur für Contao 4.10.
Warum das der CM anbietet, keine Ahnung. Der CM muss also expliziet die neuste Version statt einer passenden angefordert haben.
