### ISSUE TITLE
Contao 4.12-RC1: BugBuster\VisitorsBundle\Controller\VisitorsController" has no container set

### ISSUE THREAD

**Issue by Seefahrer** [BugBuster1701/contao-visitors-bundle#107]
Contao 4.12-RC1:
Clicking on the „info“ Icon (Origin of top 30 visitors) in the backend results in fllwg error message:

`"BugBuster\VisitorsBundle\Controller\VisitorsController" has no container set, did you forget to define it as a service subscriber?`

**Comment by BugBuster1701** [comment]
- Visitors Version?
- Symfony Version?

**Comment by Seefahrer** [comment]
Symfony ^5.2
Visitors 1.6.4 und 1.7-RC2

**Comment by Seefahrer** [comment]
Adding fllwg service to the services.yml will fix the issue:

    BugBuster\VisitorsBundle\Controller\VisitorsController:
        public: true
        calls:
            - method: setContainer
              arguments: [ '@service_container' ]

**Comment by BugBuster1701** [comment]
https://github.com/BugBuster1701/contao-visitors-bundle/pull/108

**Comment by BugBuster1701** [comment]
https://github.com/BugBuster1701/contao-visitors-bundle/issues/105

**Comment by BugBuster1701** [comment]
Kommt mir der 1.6.11 und wird in der 1.7er Version mit übernommen

**Comment by BugBuster1701** [comment]
In 1.7.0-RC3 übernommen
