### ISSUE TITLE
Contao 4.13.0-RC1: Attempted to call an undefined method named "fetch"

### ISSUE THREAD

**Issue by Seefahrer** [BugBuster1701/contao-visitors-bundle#112]
After installation of Contao 4.13.0-RC1 the site is no longer reachable but a blank page will be generated when having installed the "**Visitors-Bundle 1.7.0-RC3**". Fllwg error will be reported in „var/logs“:

``[2022-01-18T10:05:43.674787+01:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "fetch" of class "Doctrine\DBAL\Statement"." at /www/htdocs/w00c556f/cmsc4ME/vendor/bugbuster/contao-visitors-bundle/src/Controller/FrontendModule/VisitorsFrontendController.php line 598 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\UndefinedMethodError(code: 0): Attempted to call an undefined method named \"fetch\" of class \"Doctrine\\DBAL\\Statement\". at /www/htdocs/w00c556f/cmsc4ME/vendor/bugbuster/contao-visitors-bundle/src/Controller/FrontendModule/VisitorsFrontendController.php:598)
``

**Comment by BugBuster1701** [comment]
Da gibt es wohl noch mehr mit der neuen Doctrine
- https://github.com/rectorphp/rector/issues/5681

Info für mich: https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/data-retrieval-and-manipulation.html#data-retrieval

**Comment by BugBuster1701** [comment]
gehört zu #83
