### ISSUE TITLE
Legende wird in manchen Browsern nicht angezeigt

### ISSUE THREAD

**Issue by grashalm4u** [BugBuster1701/contao-visitors-bundle#115]
Ich benutze Contao 4.13.2 mit dem vistors bundle 1.7.0. Ich habe lange Zeit ein angepasstes _fe_all-Template benutzt, dass ich jetzt weggelassen habe, weil ich Anpassungen in der Zeilenreihenfolge des Counters im Frontend mit CSS vorgenommen habe.
Nach der Aktualisierung zeigte der Firefox keine Probleme, im Chrome und im Opera wurden die Legende und die CSS-Änderungen nicht mehr angezeigt, auch nach Löschen des Shared-Caches in der Systemwartung nicht.
Erst nach generellem Abschalten des Cache im Startpunkt der Website und anschließendem erneuten Löschen des Shared Cache funktionierten die Legende und die gemachten CSS-Änderungen im Chrome und im Opera wieder. Nach wiederholtem Anschalten des Cache traten die im Chrome und im Opera festgestellten Fehler erneut auf.

Grüße, grashalm

P.S.: Habe eben noch festgestellt, dass das Tausender-Trennzeichen nicht funktioniert, obwohl es angehakt ist.

**Comment by BugBuster1701** [comment]
Damit wären es nun zwei, und ich kann es immer noch nicht nachstellen. Das wird ein wenig dauern.
[Forum](https://community.contao.org/de/showthread.php?82816-Contao-Visitors-Bundle-1-7-0-(ab-Contao-4-13)&p=556979&viewfull=1#post556979)

**Comment by BugBuster1701** [comment]
Lösung wird sein: https://docs.contao.org/dev/framework/translations/#translations-within-contao-php-templates
Test läuft.

**Comment by grashalm4u** [comment]
Ja, das ist natürlich auch eine Möglichkeit! Bin gespannt, ob's klappt ;-)

**Comment by grashalm4u** [comment]
Hallo BugBuster1701,
das hat wunderbar geklappt! Die Legende ist jetzt auch wieder in Google Chrome und im Opera Browser zu sehen. Vielen Dank für die schnelle Beseitigung des Bugs! Und das Tausender-Trennzeichen ist auch wieder da: im Firefox und Chrome ist es ein Punkt, im Opera ein Komma-Zeichen. Nochmals vielen Dank! Super Arbeit!

grashalm
