### ISSUE TITLE
fehlermeldung im frontend beim debug-modus

### ISSUE THREAD

**Issue by grashalm4u** [BugBuster1701/contao-visitors-bundle#119]
Hallo BugBuster1701,

habe leider noch 'ne weitere Meldung bezüglich des Visitors-Bundles:
Diesmal bei Contao 4.13.4 und Visitors Bundle 1.7.1. War aber auch bei 1.6 schon der Fall.
Wenn ich im Backend den Debug-Modus aktiviere, zeigt er mir im Frontend oben folgenden Fehler an:
"Warning: Undefined variable $VisitorsAverageVisitsValue". Darunter steht im ersten aufklappbaren Feld noch:
"In vendor/bugbuster/contao-visitors-bundle/src/Controller/FrontendModule/VisitorsFrontendController.php (line 205)"
Kann ich selbst was tun, damit der Fehler verschwindet, oder ist das noch ein weiterer Bug? 
Bin leider ziemlich ahnungslos. Ich weiß nur: Bei mir zeigt er keinen Average-Wert an, und das soll auch so bleiben!

grashalm

**Comment by BugBuster1701** [comment]
Ist ein Logik Problem, bzw. durch PHP 8 gekommen, da wird es schärfer geprüft.
Werde ich beheben.

**Comment by grashalm4u** [comment]
Danke für das schnelle Fixen! Läuft jetzt wieder einwandfrei.
