### ISSUE TITLE
seitenzugriffe zählen falsch

### ISSUE THREAD

**Issue by grashalm4u** [BugBuster1701/contao-visitors-bundle#121]
hallo bugbuster,

ich habe vor wenigen tagen 2 neue seiten (texte) auf meine homepage gesetzt:
[https://die-schreibmaus.de/texte/viel-zu-frueh.html](https://die-schreibmaus.de/texte/viel-zu-frueh.html) und [https://die-schreibmaus.de/texte/noch-nie-so-nah.html](https://die-schreibmaus.de/texte/noch-nie-so-nah.html). auf beiden seiten werden die seitenzugriffe falsch angezeigt (mit über 1700 aufrufen; ich weiß nicht, woher er diese zahl nimmt).
die seitenzugriffe werden werden nur dann richtig angezeigt, wenn ich a) im backend eingeloggt bin, und b) ich in der root page den internen cache deaktiviere. oftmals muss ich nach einer änderung einer der beiden bedingungen die seite zweimal neu laden, damit das jeweilige verhalten sichtbar wird. getestet auf contao 4.13.4 mit visitors bundle 1.7.2 auf firefox und chrome. auf älteren seiten konnte ich das verhalten noch nicht feststellen.

**Comment by grashalm4u** [comment]
hallo bugbuster,

seit 3 tagen bekomme ich immens hohe anzahlen von besuchern online (ständig zwischen 40 und 60), besuchern heute (bis zu 1800) und zugriffen heute (zum teil über 2000) angezeigt. dies scheint mir utopisch, denn bisher haben sich die werte bei besuchern online zwischen 0 und 6, bei besuchern heute mal bis zu 200, und bei zugriffen heute mal bis zu 400 bewegt.
außerdem hat mein matomo-counter parallel eine besucher-online-anzahl von 0 attestiert.

etwa zeitgleich mit diesen hohen werten hatte ein freund, der mich beim programmieren unterstützt, den internen cache vollkommen deaktiviert. hängt das damit zusammen? muss ich den internen cache zwingend aktivieren, damit der counter einwandfrei läuft? falls ja, schalte ich ihn gerne wieder ein, aber dann habe ich wieder die probleme, die ich oben am 20. juni beschrieben habe... ist im moment irgendwie unbefriedigend...

zuletzt festgestellt mit contao 4.13.8 und visitors bundle 1.7.2 auf firefox.

bin für jede idee dankbar!

**Comment by BugBuster1701** [comment]
Um ein Bot Angriff, der nicht erkannt wird, auszuschließen, bräuchte ich zum Vergleich die Access Log vom Webserver **vom selben Zeitraum.**

**Comment by grashalm4u** [comment]
Der Zeitraum sind etwa die letzten 3 oder 4 Tage. Wo genau finde ich die Access Log-Datei auf meinem Server?

**Comment by grashalm4u** [comment]
Habe sie glaube ich gefunden, Der Log-Ordner war im Root-Verzeichnis. Hier zwei Log-files vom 14. und 15. September. Aktuellere hat er nicht...
[access_log_2022-09-14.gz](https://github.com/BugBuster1701/contao-visitors-bundle/files/9590445/access_log_2022-09-14.gz)
[access_log_2022-09-15.gz](https://github.com/BugBuster1701/contao-visitors-bundle/files/9590449/access_log_2022-09-15.gz)

**Comment by grashalm4u** [comment]
Diese überdurchschnittlich hohen Werte gibt es am 14., 15. und 16. September. Das konnte ich in der Datenbank ablesen. Heute, am 17. September, scheint es sich zu beruhigen. Aber woran erkenne ich in der access.log-Datei einen Bot und woran einen echten Besucher? Es scheint Dutzende von bots auf meinen Seiten gegeben zu haben. Kann man die logs mit den bots irgendwie ausfiltern, damit ich nachträglich noch die "richtigen Werte" zählen und in die Datenbank eintragen kann???
[access_log_2022-09-16.gz](https://github.com/BugBuster1701/contao-visitors-bundle/files/9590834/access_log_2022-09-16.gz)

**Comment by BugBuster1701** [comment]
Hab mal die vom 15.9 auf Kommandozeile grob untersucht.
Alle Seitenaufrufe die eine .html Seite aufrufen, mit HTTP Error Code 200, und alle Bot Agents ausgeschlossen (bot im Namen), ergab 1412 unterschiedliche IP Adressen = Besucher.
Darin könnten natürlich noch Bots sein, die mein BotDetection nicht erkennt.
Aber nach dem ersten Durchsehen ist mir da nichts aufgefallen.
Auffallend ist die IP "62.138.3.52", die klappert wohl alle Seiten ab wie ein Crawler.
Auch auffallend ist der Agent "... Firefox/41.0" der mit dutzenden IPs kommt, auffallend deshalb, weil Firefox 41 doch sehr alt ist und die Zugriffe zeitlich nacheinander kommen.
Wenn ich die raus nehme sind aus den 1412 noch 1193 Besucher übrig.
Das ist aber alles nur geraten. Ich bin jedoch der Meinung, das mehr Besucher sind als üblich, ist recht wahrscheinlich.

Jetzt bleibt mir noch ein Test mit Apache Benchmark mal durchzuführen um zu schauen, ob es Unterschiede gibt wenn Cache an oder aus ist. Das wäre dann aber ein Contao Problem.

**Comment by grashalm4u** [comment]
Vielen Dank schon mal bis hierher! Das heißt, wenn man alle Auffälligkeiten Richtung (unerkannter) Bots deuten und abziehen würde, würdest Du sagen, es bleiben vermutlich trotzdem noch knapp 1200 "echte" Besucher übrig. Habe ich Dich da richtig verstanden?
Aber schon irgendwie komisch, dass so ein überdimensionaler Ansturm genau drei Tage anhält, und dann wieder "zur Normalität zurückkehrt"... Vielleicht muss ich einfach nur lernen, mich darüber zu freuen???

**Comment by grashalm4u** [comment]
Hast Du noch was rausbekommen?

**Comment by BugBuster1701** [comment]
Es gibt wohl Probleme mit dem Cache, die ich allerdings nicht ganz nachvollziehen kann.
Wobei es bei mir dann zu gar keiner Zählung kommt, nicht zu viel.

**Comment by BugBuster1701** [comment]
Falls du mit eigenen Visitors Frontend Templates arbeitest zum Anzeigen der Zahlen:

- https://github.com/BugBuster1701/contao-visitors-bundle/issues/127

**Comment by grashalm4u** [comment]
Habe vor längerer Zeit mal ein angepasstes Template benutzt, mittlerweile verwende ich nur noch die Original-Templates.
Ich kann leider überhaupt nicht beurteilen, ob die Verwendung des contao-internen Caches möglicherweise zur Erhöhung meiner Zahlenwerte beigetragen hat. Habe den Cache schon seit einigen Wochen dauerhaft deaktiviert. Mittlerweile haben sich ja -wie oben bereits erwähnt- die Besucherzahlen auch wieder relativiert. Kann im Moment keine Auffälligkeiten beobachten.
