### ISSUE TITLE
Show counter per page in FE

### ISSUE THREAD

**Issue by Ernestopheles** [BugBuster1701/contao-visitors-bundle#123]
feature request: Would be nice to show individually for each page in the FE the number of visitors today, yesterday and total. As far as i can see the FE modul shows number of visitors aggregated over all pages.

**Comment by grashalm4u** [comment]
The value display for the total views of each individual page is already included. However, the value display for the views today and yesterday for each individual page is not yet. The question is whether these details are so important to you. At the time, I wanted to be able to at least see the total number of views of each individual page, and Bugbuster integrated that a long time ago.

**Comment by BugBuster1701** [comment]
For understanding, you want to have:
- Page Visits today
- Page Visits yesterday
- Page Visits total


Correct?

**Comment by Ernestopheles** [comment]
Right
