### ISSUE TITLE
What to do with BotDetectionDemo?

### ISSUE THREAD

**Issue by Aybee** [BugBuster1701/contao-visitors-bundle#125]
Is it necessary to create a BotDetectionDemo module and insert it into the FE?

**Comment by BugBuster1701** [comment]
No, it is not necessary.

**Comment by BugBuster1701** [comment]
This allows BotDetection to be tested independently, which is better for developers and for troubleshooting.

**Comment by Aybee** [comment]
Ok, thank you 👍
