### ISSUE TITLE
PHP Warning:  Undefined array key "deleteConfirm"

### ISSUE THREAD

**Issue by bizon1** [BugBuster1701/contao-visitors-bundle#128]
Contao 4.13.12
PHP 8.1.12
contao-visitors-bundle 1.6.13

After clearing the Symfony caches the following PHP Warning appears:
`PHP Warning:  Undefined array key "deleteConfirm" in .../vendor/bugbuster/contao-visitors-bundle/src/Resources/contao/dca/tl_visitors.php on line 85`

Changing the dca settings on line 85 with:
`'attributes' => 'onclick="if (!confirm(\''.($GLOBALS['TL_LANG']['MSC']['deleteConfirm'] ?? null).'\')) return false; Backend.getScrollOffset();"',`
is fixing this issue.

**Comment by BugBuster1701** [comment]
Is fixed in Version 1.7.1
https://github.com/BugBuster1701/contao-visitors-bundle/issues/118
