### ISSUE TITLE
PHP-Warnung: Undefined array key 1

### ISSUE THREAD

**Issue by do-while** [BugBuster1701/contao-visitors-bundle#145]
In unregelmäßigen Abständen finde ich die folgende Meldung im Server-Log (nicht im Contao-Log, da gibt es dazu keinen Eintrag):
_AH01071: Got error 'PHP message: PHP Warning: Undefined array key 1 in .../vendor/bugbuster/contao-visitors-bundle/src/Resources/contao/classes/ModuleVisitorBrowser3.php on line 718_

Die Meldung kommt immer von IP 91.186.39.110

[https://github.com/BugBuster1701/contao-visitors-bundle/blob/dc3fb08a228053b8c4e6c3c3356530af81c4a528/src/Resources/contao/classes/ModuleVisitorBrowser3.php#L718C53-L718C53](https://github.com/BugBuster1701/contao-visitors-bundle/blob/dc3fb08a228053b8c4e6c3c3356530af81c4a528/src/Resources/contao/classes/ModuleVisitorBrowser3.php#L718C53-L718C53)

**Comment by BugBuster1701** [comment]
Interessant wäre der User-Agent die der Zugriff von der IP mitbringt.

**Comment by do-while** [comment]
Ich muss suchen, die Zugriffs-Logs haben ca. 600.000 Zeilen pro Tag. IP habe ich auf die Schnelle nicht darin gefunden.

**Comment by BugBuster1701** [comment]
Dann suche mal nach "EdgiOS", da muss einer bei sein, der keine Minorversion dahinter hat, also z.B. statt "...EdgiOS/41.1.35.1" nur "... EdgiOS/41"

**Comment by do-while** [comment]
Ich habe ihn erwischt kommt doch mit unterschiedlichen IPs aus dem Bereich 91.168.xxx.xxx (aber alle mit identischem UserAgent):

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/116 Version/13.0.3 Safari/605.1.15

Scheint aber kein Bot zu sein, denn CSS und Bilder werden nachgeladen.
Ich hoffe, damit kannst Du etwas anfangen.

**Comment by BugBuster1701** [comment]
Fixed in Version 1.8.4
