### ISSUE TITLE
Installation unter Contao 5.3 bricht ab

### ISSUE THREAD

**Issue by Schmidty2** [BugBuster1701/contao-visitors-bundle#162]
Hallo,
die Installation unter Contao 5.3 bricht ab.
Contao 5.3.1
Provider All-Inkl
PHP 8.3.3

Es ist wohl ein Conflict mit monolog, hier die Ausgabe des Contao-Managers:

> Problem 1
>     - monolog/monolog[2.0.0, ..., 2.0.2] require php ^7.2 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - Root composer.json requires bugbuster/contao-visitors-bundle ^1.10 -> satisfiable by bugbuster/contao-visitors-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3].
>     - bugbuster/contao-visitors-bundle[1.10.0, ..., 1.10.3] require contao/core-bundle ^5.2 -> satisfiable by contao/core-bundle[5.2.0, ..., 5.3.1].
>     - contao/core-bundle[5.2.0, ..., 5.3.1] require monolog/monolog ^2.0 -> satisfiable by monolog/monolog[2.0.0, ..., 2.9.2].
>     - You can only install one version of a package, so only one of these can be installed: monolog/monolog[1.11.0, ..., 1.27.1, 2.0.0, ..., 2.9.2, 3.0.0, ..., 3.5.0].
>     - Conclusion: don't install one of monolog/monolog[3.5.0], contao/core-bundle[5.3.1] (conflict analysis result)
>     - Conclusion: install monolog/monolog 3.5.0 (conflict analysis result)

Und hier die Composer.json
```
{
    "type": "project",
    "require": {
        "cliffparnitzky/checked-email": "^2.1",
        "contao/calendar-bundle": "5.3.*",
        "contao/comments-bundle": "5.3.*",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "5.3.*",
        "contao/listing-bundle": "5.3.*",
        "contao/manager-bundle": "5.3.*",
        "contao/news-bundle": "5.3.*",
        "contao/newsletter-bundle": "5.3.*",
        "inspiredminds/contao-extended-form-fields": "^2.8",
        "madeyourday/contao-rocksolid-columns": "^2.1",
        "madeyourday/contao-rocksolid-custom-elements": "^2.4",
        "madeyourday/contao-rocksolid-icon-picker": "^2.1",
        "madeyourday/contao-rocksolid-mega-menu": "^2.2",
        "madeyourday/contao-rocksolid-slider": "^2.2",
        "madeyourday/contao-rocksolid-theme-assistant": "^2.1",
        "numero2/contao-proper-filenames": "^2.1",
        "terminal42/contao-leads": "^3.0",
        "terminal42/notification_center": "^2.0",
        "trilobit-gmbh/contao-tiles-bundle": "^2.0"
    },
    "extra": {
        "public-dir": "public",
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "@php vendor/bin/contao-setup"
        ],
        "post-update-cmd": [
            "@php vendor/bin/contao-setup"
        ]
    }
}
```

**Comment by BugBuster1701** [comment]
Hast du im Manager bei Installieren von Visitors unten "Änderungen anwenden -> Alle Pakete aktualisieren" ausgewählt?

**Comment by Schmidty2** [comment]
> Hast du im Manager beim Installieren von Visitors unten "Änderungen anwenden -> Alle Pakete aktualisieren" ausgewählt?

Ja, habe ich (auch  bei den anderen Paketen mit dem selben Problem)
Ich habe Deine Pakete einzeln installiert, überall wo das monolog-Problem aufgetreten ist, habe ich ein Ticket erstellt

Danke für's fixen

**Comment by BugBuster1701** [comment]
Ich weiß noch nicht wie ich das tun soll, außer selber eine Monolog Version anzufordern die hoch genug ist, das diese für PHP8  passt.
Irgendwas bei dir zieht die Monolog Version so weit runter, das nur eine für PHP7 dabei raus kommt, und das passt dann natürlich nicht.

**Comment by Schmidty2** [comment]
Ich habe gerade in einer neuen, extra für die Tests installierten Contao-Installation versucht, Visitors zu installieren.
Leider ohne Erfolg.
All-Inkl Premium-Paket
PHP 8.3.3
ContaoManager 1.8.4
Contao 5.3.1, keine weiteren Erweiterungen installiert

>   Problem 1
>     - monolog/monolog[2.0.0, ..., 2.0.2] require php ^7.2 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - Root composer.json requires bugbuster/contao-visitors-bundle ^1.10 -> satisfiable by bugbuster/contao-visitors-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3].
>     - bugbuster/contao-visitors-bundle[1.10.0, ..., 1.10.3] require contao/core-bundle ^5.2 -> satisfiable by contao/core-bundle[5.2.0, ..., 5.3.1].
>     - contao/core-bundle[5.2.0, ..., 5.3.0] require monolog/monolog ^2.0 -> satisfiable by monolog/monolog[2.0.0, ..., 2.9.2].
>     - You can only install one version of a package, so only one of these can be installed: monolog/monolog[1.11.0, ..., 1.27.1, 2.0.0, ..., 2.9.2, 3.0.0, ..., 3.5.0].
>     - Conclusion: don't install one of monolog/monolog[3.5.0], contao/core-bundle[5.3.1] (conflict analysis result)
>     - Conclusion: install monolog/monolog 3.5.0 (conflict analysis result)

composer.json siehe https://github.com/BugBuster1701/contao-botstatistics-bundle/issues/18#issuecomment-1988573720
