### ISSUE TITLE
Contao 5.3 Demo CSS Dateien werden im HEADER eingebunden

### ISSUE THREAD

**Issue by chriza** [BugBuster1701/contao-visitors-bundle#173]
in meiner frischen Contao 5.3.11 Installation werden folgende CSS-Dateien im Header eingebunden.

![image](https://github.com/BugBuster1701/contao-visitors-bundle/assets/1572887/cea8e611-1aa9-4e64-aa2a-84edd6354f9c)

Mit freundlichen Grüßen
Christoph Zander

**Comment by BugBuster1701** [comment]
Wurde ein Theme installiert?
Wenn die Installation frisch ist, dann ohne Erweiterungen, oder?
Zur Klarstellung, das geht gar nicht das die Demo CSS automatisch eingebunden werden.
Diese müssen ja, theoretisch, im Layout bei externe CSS eingebunden werden. Sind die da zu finden?

**Comment by BugBuster1701** [comment]
ach das sehe ich jetzt erst. Die Dateien werden direkt aus dem public Ordner eingebunden, gar nicht über files.
Das habe ich noch nie gesehen. Das wäre dann eine Neuerung in 5.3.11, ohne Vorankündigung.
Muss ich mal versuchen nachzustellen.

**Comment by BugBuster1701** [comment]
Es wird nichts automatisch eingebunden. Hast du vielleicht eine Erweiterung die das macht installiert?
Oder wie gesagt ein Theme was meine Erweiterungen mitbringt und diese gleich einbindet?

**Comment by BugBuster1701** [comment]
So, jetzt habe ich was gefunden. Eingebunden wird nicht die Demo FE CSS von Visitors, sondern eine basis css mit nur einem Eintrag `.mod_visitors .invisible`.
Der stört jetzt nicht wirklich, aber ich schaue mal warum und ob ich das anders machen kann.

**Comment by BugBuster1701** [comment]
Die Datei "mod_visitors_basic.css" ist nun aus dem css_demo Ordner raus genommen worden. Das führte wohl zu der Annahme, es wäre eine Demo CSS.
Ist es aber nicht, die ist für alle Frontend Module notwendig, egal welches Template gewählt wird.

Besonders bei der Wahl von "mod_visitors_fe_invisible", denn dort wird nur dieses basic css benötigt um den Zähl-HTML-Tag nicht das Layout stört. Nutzer brauchen dann dazu nichts weiter tun.
