### ISSUE TITLE
[PHPOffice/PhpSpreadsheet] hochheben auf 2.*

### ISSUE THREAD

**Issue by berecont** [BugBuster1701/contao-visitors-bundle#180]
Hier gibt es eigentlich schon einen Zweig mit 2.* .  
[https://github.com/PHPOffice/PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet)  

Davon dürften Installationen 4.13 und 5.3 betroffen sein.
Wird es dahingehend Anpassungen geben bzw. einen möglichen Zeitplan dazu?

**Comment by BugBuster1701** [comment]
Laut vuldb sind nur die 2.0, 2.1, 2.2 betroffen, Fix ist in 2.2.1 enthalten.
https://vuldb.com/de/?id.276049
Die Version 2.x unterstützt kein PHP 7.4 mehr. Wenn ich also auch für 4.13 ein Update bringe, dann muss ich den PHP 7.4 Support entfernen:
Ob das notwendig ist für Version 1.x, muss noch geprüft werden, nach der Anleitung.
https://github.com/BugBuster1701/contao-visitors-bundle/security/dependabot/2

Zeitplan kann ich nicht geben, so wie ich Zeit dafür finde.

**Comment by BugBuster1701** [comment]
Für Contao 5.3 ist die Version 1.13.4 nun mit PhpSpreadsheet 2.x freigegeben

**Comment by BugBuster1701** [comment]
Für Contao 4.13 ist die Version 1.8.6  nun mit PhpSpreadsheet 2.x freigegeben
