### ISSUE TITLE
Logged in Backend-User is counted in Frontend (contao 4.5)

### ISSUE THREAD

**Issue by baumisimon** [BugBuster1701/contao-visitors-bundle#31]
In contao < 4 a logged in backend user was not counted when viewing frontend preview.
This exclusion doesn't seem to work in contao 4, so that I get counted in frontend even if logged in in the backend.

**Comment by BugBuster1701** [comment]
4me: Sessionverwaltung hat sich geändert ab 4.5, Anpassung nötig über Versionsweiche.

**Comment by BugBuster1701** [comment]
- [x] Insert Tag
- [ ] Frontend Controller
