### ISSUE TITLE
Hinweise nicht lesbar / abgeschnitten

### ISSUE THREAD

**Issue by Schmidty2** [BugBuster1701/contao-visitors-bundle#32]
Unter Contao 4.4.13 sind bei der Übersicht einige Elemente nicht lesbar, weil diese abgeschnitten bzw. überdeckt sind. Das Ganze wird erst sichtbar, wenn man die Statistiken mit den drei Punkten öffnet. Details in diesem Screenshot:
![visitors](https://user-images.githubusercontent.com/2067428/36076971-38cef474-0f64-11e8-8dfb-77227d29a792.JPG)

**Comment by BugBuster1701** [comment]
Das ist Absicht, man soll sehen das dort noch mehr ist, wenn man das aufklappt.
Wäre es sinnvoller das  nicht zu tun? Käme man dann auf die Idee, die Punkte anzuklicken?

**Comment by Schmidty2** [comment]
Es geht nicht um die drei Punkte, deren Funktion ist klar (das war bei der Contao 3.5-Version der grüne Pfeil). Die drei Punkte sind bei obigem Screenshot bereits angeklickt und es ist der komplette Bereich sichtbar (Die Homepage im Screenshot ist erst seit kurzem online, deshalb gibt es hier noch nicht viele Daten).
Der Screenshot zeigt bereits den **aufgeklappten Zustand**, da sieht man dann, dass unten noch ein Satz stehen soll. Wenn man das _nicht lesbare_ markiert, kopiert und in einen Editor einfügt, werden die Zeilen "_Werte aus den Daten der letzten 60 Tage._" bzw. "_Werte aus den Daten der letzten 120 Tage._" im Editor sichtbar.
Diese Sätze sollen doch sicher im Backend im aufgeklappten Zustand komplett lesbar sein. Zumindest waren es in der alten Version unter Contao 3.5 so:
![visitors-2](https://user-images.githubusercontent.com/2067428/36077643-bb483a92-0f6d-11e8-8494-9a826c954d68.JPG)
Ob es drei Punkte zum Aufklappen sind oder ein Pfeil ist Ansichtssache, der Pfeil war besser zu sehen (finde ich). Eventuell sollte man die drei Punkte etwas besser hervorheben?

Bei Bedarf kann ich per PN einen Backend-Zugang zur Contao-Installation bereitstellen.

**Comment by BugBuster1701** [comment]
Aja, das schaue ich mir mal an.
Die Punkte finde ich auch nicht so super, ist halt vom Backen Theme vorgegeben, ich habe die schon über css verstärkt und gefärbt, damit man die überhaupt sieht.

**Comment by BugBuster1701** [comment]
Ich hoffe das ist nun so besser. Bei mir jedenfalls schon.
