### ISSUE TITLE
Feature: DNT: Do Not Track

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/contao-visitors-bundle#34]
Nicht zählen wenn Browser DNT übermittelt.

https://www.pixelfreu.de/blog/details/items/dnt-do-not-track.html

**Comment by BugBuster1701** [comment]
Berechtigter Einwand: Würde denn Visitors dann überhaupt noch was zählen? 
(Bots sind ja auch schon unterdrückt, nun auch noch Menschen)

**Comment by Schmidty2** [comment]
Zitat:
Bots sind ja auch schon unterdrückt,...

wieso lösen diese dann einen 404 aus und die 404er Zugriffe von Bots werden gezählt? Siehe [https://community.contao.org/de/showthread.php?70669-Viele-Error404-Zugriffe-in-der-Visitors-Statistik-sichtbar&p=472915&viewfull=1#post472915](https://community.contao.org/de/showthread.php?70669-Viele-Error404-Zugriffe-in-der-Visitors-Statistik-sichtbar&p=472915&viewfull=1#post472915)

**Comment by BugBuster1701** [comment]
Was hast du in der htaccess stehen, das nicht gefundene png Dateien zu Contao umgelenkt werden?

**Comment by BugBuster1701** [comment]
Ah merke grad das macht die htaccess von Contao 4 sogar selbst.
Habe mal auch eine 404 angelegt und teste das mal.

**Comment by BugBuster1701** [comment]
Fehler auf 404 Seite: https://github.com/BugBuster1701/contao-visitors-bundle/issues/36
