### ISSUE TITLE
process terminated with exit code 137

### ISSUE THREAD

**Issue by mmiat** [BugBuster1701/contao-visitors-bundle#35]
i've tried to install contao-visitors-bundle in my contao  4.4.18 fresh installation
it failed, see screenshot
it seems installed but no database update are available in install tool and module is not in contao backend
now i removed, also the uninstall process was killed
thanks

-------------------------------------------- installation -------------------------------------------- 

![screenshot 2018-05-26 13 12 13](https://user-images.githubusercontent.com/11910225/40575580-b45dc7a8-60e7-11e8-8760-080ff32c0cb6.png)

-------------------------------------------- seems installed -------------------------------------------- 

![screenshot 2018-05-26 13 13 36](https://user-images.githubusercontent.com/11910225/40575581-b489d3a2-60e7-11e8-8846-d05f45d6cde8.png)

-------------------------------------------- uninstall -------------------------------------------- 

![screenshot 2018-05-26 13 18 57](https://user-images.githubusercontent.com/11910225/40575579-b432da7a-60e7-11e8-9f9d-8acb930acf5d.png)

**Comment by BugBuster1701** [comment]
Your max_execution_time is to less, PHP killed the Process from Composer.
Try first Update Packages and then install visitors.

**Comment by mmiat** [comment]
the problem is manager, it has some problem: 
https://github.com/contao/contao-manager/issues/90
https://github.com/contao/contao-manager/issues/259
