### ISSUE TITLE
Umlenkung auf 404 Seite durch Bots werden gezählt

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/contao-visitors-bundle#36]
```
[ModuleVisitorsTag::replaceInsertTagsVisitors] [163] BOT: 1
[ModuleVisitorsTag::replaceInsertTagsVisitors] [164] SE : 0
[ModuleVisitorsTag::replaceInsertTagsVisitors] [170] Counted Server: True
```
Bot wird also erkannt  :confused:

**Comment by BugBuster1701** [comment]
Test über Kommandozeile:
`curl --user-agent Googlebot/2.1  http://contao.test/blafasel.html`

**Comment by BugBuster1701** [comment]
Beim besten Willen, ich kann das nicht nachstellen.
Selbst wenn ich mit dem AhrefsBot teste:
`curl --user-agent "Mozilla/5.0 (compatible; AhrefsBot/5.2; +http://aom/robot/)" ....`

**Comment by Schmidty2** [comment]
Bringen Dich ein Backend-Zugang, ein FTP-Zugang und die Server-Logs weiter?
Wenn ja kann ich diese Infos per PN gerne bereitstellen.

**Comment by BugBuster1701** [comment]
Siehe Forum.
