### ISSUE TITLE
BE Statistik: Rücksetzung nur für bestimmte Benutzergruppen erlauben

### ISSUE THREAD

**Issue by Schmidty2** [BugBuster1701/contao-visitors-bundle#39]
Siehe https://github.com/BugBuster1701/visitors/issues/224

Ist eigentlich in dieser Version noch wichtiger, da ja der 3er Zweig wegfallen wird.
Danke 😀

**Comment by BugBuster1701** [comment]
- [x] Einstellung in der Kategorie
- [ ] Abfrage der Erlaubnis in der Statistik
- [ ] Anpassung des Templates (Ein-/Ausblenden)
- [ ] setZero Anpassung, Erlaubnis prüfen
