### ISSUE TITLE
Version 1.3.5 schmeißt bei mir den Error

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/contao-visitors-bundle#50]
"Unable to generate a URL for the named route "visitors_frontend_screencount" as such route does not exist." hat das mit diesem Issue hier zu tun?

_Originally posted by @Coding-Kiwi in https://github.com/BugBuster1701/contao-visitors-bundle/issues/21#issuecomment-440973121_

**Comment by BugBuster1701** [comment]
Welche Contao Version? Welche Symfony Version?

**Comment by Coding-Kiwi** [comment]
Entschuldigung für die fehlenden Angaben, ich war wohl etwas in Eile
Contao Version 4.4.28
Symfony Version 3.4.18
Modul Version 1.3.5

ich hatte das Problem gelöst, indem ich
```
BugBusterVisitorsBundle:
    resource: "@BugBusterVisitorsBundle/Resources/config/routing.yml"
```

in die `app/config/routing.yml` gepackt und den Cache erneuert habe; Wenn ich den Fehler allerdings nun reproduzieren möchte indem ich das wieder aus der routing.yml entferne, cache leere etc. , bekomme ich es nicht mehr hin.. also vermute ich, dass es lediglich eine Cache-bedingte Sache war

Vielen Dank für die schnelle Rückmeldung

**Comment by BugBuster1701** [comment]
Wird wohl so sein, obwohl der Cache ja eigendlich gelöscht wird bei der Installation.
Die routing.yml wird im Normalfall vom Contao Manager Pluglin geladen.
https://github.com/BugBuster1701/contao-visitors-bundle/blob/master/src/ContaoManager/Plugin.php#L43
