### ISSUE TITLE
Contao 4.8.1 Besuchervorlagen werden nicht mehr gefunden

### ISSUE THREAD

**Issue by chriza** [BugBuster1701/contao-visitors-bundle#65]
![grafik](https://user-images.githubusercontent.com/1572887/64066518-3a8ccc80-cc1b-11e9-837a-c665003cba9a.png)

**Comment by BugBuster1701** [comment]
Fehler hat zwei Ursachen, ein Bug in Contao 4.8.1 und eine API Änderung die nötig ist wenn der Fix eingebaut wurde.

- https://github.com/contao/contao/issues/677
- getTemplateGroup hat zweiten Parameter bekommen, den ich bisher auch übergeben habe aber nicht nötig ist. Der stört nun. Neue Version kommt die dann kompatibel mit Contao 4.8.2 sein wird.
