### ISSUE TITLE
Nicht installierbar unter Contao 4.4

### ISSUE THREAD

**Issue by Coding-Kiwi** [BugBuster1701/contao-visitors-bundle#70]
Da `contao/core-bundle: ~4.7` als dependency aufgelistet ist, lässt sich das Bundle ab Version 1.5.3 unter Contao 4.4 nicht mehr über composer installieren.

```
Problem 1
    - Conclusion: don't install bugbuster/contao-visitors-bundle 1.6.1
    - Installation request for bugbuster/contao-visitors-bundle ^1.6 -> satisfiable by bugbuster/contao-visitors-bundle[1.6.0, 1.6.1].
    - Conclusion: don't install contao-components/contao 7.1.5
    - bugbuster/contao-visitors-bundle 1.6.0 requires contao/core-bundle ~4.7 -> satisfiable by contao/core-bundle[4.7.0, 4.7.1, 4.7.2, 4.7.3, 4.7.4, 4.7.5, 4.7.6, 4.7.7, 4.8.0, 4.8.1, 4.8.2, 4.8.3, 4.8.4].
```

Ich muss manuell Version 1.5.2 in die composer.json eintragen.
Ich poste es hier als issue, da Contao Version 4.7 kein LTS ist laut https://contao.org/de/release-plan.html und die dependency daher in meinen Augen fragwürdig ist.

**Comment by Coding-Kiwi** [comment]
Also was ich sagen will ist, dass wir firmenintern nur LTS Versionen von Contao verwenden, die momentane LTS Version ist eben 4.4 und solange 4.9 noch nicht LTS ist finde ich sollte das bundle nicht 4.7 als dependency fordern

**Comment by BugBuster1701** [comment]
Da bin ich in eine Falle von Composer getappt. Composer versucht die neuste Minor Version, derzeit 1.6.x, zu installieren, wenn man keine Version angibt, geht aber nicht rückwärts durch um passende Versionen zu finden. (das tut Composer dummerweise nur bei einer Abhängigkeitsauflösung)

Da die 1.6.x bereits Anpassungen hat die nur ab Contao 4.7 funktionieren, kann ich das auch nicht rückgängig machen.

Zum Installieren kann als Version `^1.0` eingetragen werden, dann wird die maximal gültige von Composer gesucht.

**Comment by BugBuster1701** [comment]
Hinweis dazu in der Readme eingetragen.
