### ISSUE TITLE
FE: Keine Anzeige des Tagesdurchschnitts

### ISSUE THREAD

**Issue by Anke** [BugBuster1701/contao-visitors-bundle#71]
Hallöchen,

ich bin gerade dabei, eine Website von 3.5.40 auf 4.8.5 zu updaten und stelle fest, dass in beiden Versionen im Frontend die Zahl der durchschnittlichen täglichen Besucher nicht mehr angezeigt wird - in keinem der FE-Templates. Keine Fehlermeldungen. Im BE sind die Durchschnittswerte vorhanden. 

VG
Anke

**Comment by BugBuster1701** [comment]
Welche Werte haben die Durchschnittswerte im Backend?
Es sei zu Bemerken, das die Werte dort für die letzten 30 / 60 Tage sind.
Im Frontend jedoch für den gesamten gezählten Zeitraum. Wenn du nur wenig Besucher hast, kann es sein, das der Gesamtdurchschnitt unter 0,5 kommt und gerundet dann 0 ergibt.

**Comment by Anke** [comment]
Besucher pro Tag/30/60: 16,97 / 23,50 / 21,52

In diesem Fall ist die fehlende Angabe kein Beinbruch, ich suche nur nach dem Grund. Ich betreue eine weitere Vereinswebsite und dort wird der Durchschnitt mit 132 pro Tag ausgegeben.

mod_visitors_fe_visits habe ich zwar geändert, aber nur zu Formatierungszwecken. Mit dem Originaltemplate und mit mod_visitors_fe_all wird der Durchschnitt ebenfalls nicht angezeigt.

**Comment by BugBuster1701** [comment]
Hmm, dann sollte wirklich auch die 16,96 auf 17 gerundet, im Frontend erscheinen.
Werde ich mal tiefer debuggen müssen, ob ich da eine Variante finde, wo das nicht greift.

**Comment by BugBuster1701** [comment]
Kannst du mit einen DB Tool mal folgendes Aufrufen und das Ergebnis hier posten? (von der DB der Seite wo 0 erscheint im Frontend)
```
SELECT VID, SUM(visitors_visit) AS SUMV, MIN( visitors_date ) AS MINDAY 
FROM tl_visitors_counter
GROUP BY 1
```

**Comment by BugBuster1701** [comment]
Hinweis: "Übrigens wird nicht "0" ausgegeben, sondern gar nichts - falls das einen Unterschied macht."
