### ISSUE TITLE
Version 1.5.2 verursacht 'weisse Seite' im Frontend

### ISSUE THREAD

**Issue by berecont** [BugBuster1701/contao-visitors-bundle#76]
Version 1.5.2 verursacht 'weisse Seite' im Frontend.  
Contao 4.4.48  
php7.4.3  
Installation via Contao Manager in eine vorhandene Installation mit den Einstellungen ^1.0  
  
Der Fehler konnte auf das template eingeschränkt werden. In Verwendung ist/war mod_visitors_fe_invisible.html5.  

Ein Austausch auf ein manueller aktuelleres Template hatte den Fehler behoben.  
Evtl. ein php-Versions-Thema?

[thread dazu im Forum](https://community.contao.org/de/showthread.php?77847-Modul-im-Layout-eingebunden-bringt-weisse-Seite)  

der aktuell funktionierende Inhalt im template:  

    
    
    <?php foreach ($this->visitors as $visitor): ?>
    <span class="visitor_count invisible">{{cache_visitors::<?= $visitor['VisitorsKatID']; ?>::count}}</span>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
        var iWidth  = window.innerWidth  || (window.document.documentElement.clientWidth  || window.document.body.clientWidth); 
        var iHeight = window.innerHeight || (window.document.documentElement.clientHeight || window.document.body.clientHeight);
        var sWidth  = screen.width;
        var sHeight = screen.height;
        var visitorurl = '<?= $this->route('visitors_frontend_screencount') ?>?vcid=<?= $visitor['VisitorsKatID']; ?>&scrw='+sWidth+'&scrh='+sHeight+'&scriw='+iWidth+'&scrih='+iHeight+'';
        try {
            fetch( visitorurl, { method: 'GET' , headers: { 'X-Requested-With': 'XMLHttpRequest', } } )
            .catch( error => console.error('error:', error) );
        } catch (r) {
            return;
        }
        
        });
    </script>
    <?php endforeach; ?>

**Comment by BugBuster1701** [comment]
Getestet mit frischer Contao 4.4.48, Visitors 1.5.2 und PHP 7.4.3 (Ubuntu 20.04).
Keine Probleme. Da der PHP Anteil beider Templates identisch ist, ist das auch nicht nachvollziehbar.
