### ISSUE TITLE
Provide PHP 8 support 

### ISSUE THREAD

**Issue by akroii** [BugBuster1701/contao-visitors-bundle#94]
Hello,
can you please provide an Support for PHP8?
```
bugbuster/contao-visitors-bundle[1.6.0, ..., 1.6.5] require php ^7.1 -> your php version (8.0.1.0) does not satisfy that requirement.
```

**Comment by BugBuster1701** [comment]
Version 1.6.6 and 1.6.7 has support for PHP8. But only für Contao 4.9+
Which version of Contao do you use?

**Comment by akroii** [comment]
I see the error in 4.11.0 when I'am using php8

**Comment by BugBuster1701** [comment]
Do you have requested the bundle with:  `^1.6`? 

> bugbuster/contao-visitors-bundle [1.6.0, ..., 1.6.5] require php ^7.1

That ist correct, but why composer not used 1.6.7?

My test installation with PHP 8 and Contao 4.11:
![grafik](https://user-images.githubusercontent.com/1218809/109403683-297f6180-795f-11eb-8436-df74f0c55d6b.png)
